# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://msu-cerl.github.io'
baseurl: ''
title: 'MSU CERL'
description: |
  We're working to demystify how college students learn to do computational work.
  <br>
  <br>
  Interested in joining us?
  <br>
  Send an email to dsilvia@msu.edu.
permalink: pretty
logo: "/assets/img/logo.png"

# Pagination
paginate: 5
paginate_path: /blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: People
  url: /people/
- title: Projects
  url: /projects/
- title: Curriculum Development
  url: /curriculumdev/
- title: Publications
  url: /pubs/

# Footer nav
navigation_footer:
- title: Return to Home
  url: .

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    feature_image: "https://picsum.photos/2560/600?image=866"
